nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ["http://localhost:5173","https://localhost:5173","https://didaskin.com","https://www.didaskin.com"]
        allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
        allow_headers:
            [
                "Content-Type",
                "Authorization",
                "X-Requested-With",
                "Accept",
                "Origin",
            ]
        expose_headers: ["Link", "X-Total-Count"]
        max_age: 3600
        allow_credentials: true
    paths:
        "^/": null